define(function() {
    return {
        "properties": [{
            "name": "enableTitle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "enableLegend",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "duration",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "noOfColumns",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "gridChartDataSet",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fontSize",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "renderType",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fontColor",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "titlePosition",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "legendPosition",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "easing",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fontFamily",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "fontStyle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": ["createChart", "render"],
        "events": ["errorCallback"]
    }
});